[entropy.misc, rigo] fix file-like objects with Python 3
FakeOutFile and LogFile need .buffer like Python 3 "text" file objects
which is needed when in rigo standard output/error is replaced, and then
it reaches Portage which does this:

	    if sys.hexversion >= 0x3000000 and fd in (sys.stdout, sys.stderr):
		    fd = fd.buffer
    fd.write(mystr)

(/usr/lib64/python3.6/site-packages/portage/util/__init__.py).

Entropy internal code did not need this.

Note, after this commit, changes done previously:
    1)
    commit 0869912ec4c630d2946e835b2585367e233c1c15

	[entropy.spm] Rigo related Python 3 fix

	  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 101, in _pusher
	    self._std.buffer.write(chunk)
	AttributeError: 'FakeOutFile' object has no attribute 'buffer'

    2)
    commit 8700aade27cb4117bf102afc7bd22ba6acfd8aa8

	[entropy.spm, rigo] Rigo related Python 3 fixes

	1)
	  File "/usr/lib/python-exec/python3.6/RigoDaemon_app.py", line 362, in _pusher
	    fobj.write(chunk)
	TypeError: write() argument must be str, not bytes

	2)
	  File "/usr/lib64/python3.6/site-packages/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 77, in __init__
	    self.buffer = Writer(self, self._std.buffer)
	AttributeError: 'FakeOutFile' object has no attribute 'buffer'

    (...)

could be likely reverted; not tested, it could be better to have them anyway to
avoid futher re/encoding/checks if conversions are needed (subjective).

Fixes bug 5899.