[entropy.spm] adapt to qfile from portage-utils-0.81
[Not tagged so in their git repository... whatever.]

With -R / it prints bogus lines making Entropy crash:

  File "/usr/lib64/python2.7/site-packages/portage/dbapi/vartree.py", line 748, in aux_get
    raise KeyError(mycpv)
KeyError: 'plib_registry:'

The change was done in portage-utils, commit f05c78008b1754a79e31e793a67d07ed8f5d11bc

    Make qfile also check the prune lib registry

and the problem with qfile was reported to Gentoo in bug 699558.

It will break with older qfile but Entropy should fallback to slower,
non-qfile code branch.